name: Test action

on:
    workflow_call:
      inputs:
        version:
          type: string
          required: false
        path:
          type: string
          default: '.'
          required: false
        cache:
          type: string
          default: 'true'
          required: false

jobs:
    test:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v4

        - name: Create manifest file
          run: |
            cat > ${{ inputs.path }}/rokit.toml << EOF
            [tools]
            rojo = "rojo-rbx/rojo@7.4.4"
            EOF
          shell: bash

        - name: Run setup-rokit
          uses: ./
          with:
            version: ${{ inputs.version }}
            path: ${{ inputs.path }}
            cache: ${{ inputs.cache }}

        - name: Verify executables in PATH on bash
          run: |
            command -v rojo
          shell: bash

        - name: Verify executables in PATH on pwsh
          run: |
            Get-Command "rojo"
          shell: pwsh